### ISSUE TITLE
Alternative substitution logic discussion

### ISSUE THREAD

**Issue by CrossEye** [broofa/BroofaJS#4]
The substitutions are all made with the most recent expression and not the closest one.

I don't know that there is any simple solution for this.  The model only advances the expression after completing a plain string.  But It can lead to things like this:

```js
simplur`There [is|are] ${1} fo[x|xes] and there [is|are] ${4} octop[us|i] in the zoo.`
//=> "There is 1 fox and there is 4 octopi in the zoo."
// when we clearly would prefer "There is 1 fox and there are 4 octopi in the zoo."
```

Here `" fo[x|xes] and there [is|are] "` is all handled in one loop iteration, when there (at least) is an argument to be made for applying `${1}` to `"fo[x|xes]"` but `${4}` to `"octop[us|i]"`.

**Comment by broofa** [comment]
Interesting use case!  Alas, a nearest-expression approach would lead to similar problems I suspect. E.g.
```
> simplur `There [is|are] ${1} reticulated giraffe[|s] and ${3} fox[|es]`
There is 1 reticulated giraffes and 3 foxes
```

Leaving this open for discussion.

**Comment by timhwang21** [comment]
```javascript
`${simplur`There [is|are] ${1} fo[x|xes]`} and ${simplur`there [is|are] ${4} octop[us|i] in the zoo.`}`
```
Gets the job done, and IMO is easy enough to understand, though it definitely is a bit code smelly!
